FROM node:22-alpine

WORKDIR /app

# Copy the root package.json and lock file to install dependencies
COPY package*.json ./

# Copy the bot package.json
COPY telegram-bot/package.json ./telegram-bot/

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY . .

# Build the Telegram Bot
RUN npm run build --workspace=telegram-bot

# Command to run in production
CMD ["npm", "run", "start", "--workspace=telegram-bot"]
