FROM node:22-alpine

WORKDIR /app

# Copy the root package.json and lock file to install dependencies
COPY package*.json ./

# We MUST copy the package.json for EVERY workspace before npm install. 
# This doesn't copy the api code! It just prevents npm from breaking the lockfile.
COPY api/package.json ./api/
COPY frontend/package.json ./frontend/
COPY telegram-bot/package.json ./telegram-bot/

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY . .

# Build the Telegram Bot
RUN npm run build --workspace=telegram-bot

# Command to run in production
CMD ["npm", "run", "start", "--workspace=telegram-bot"]
